import 'package:flutter/material.dart';

/* UndefinedNode Alamat
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAlamatWidget5 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
