import 'package:flutter/material.dart';

/* UndefinedNode Bintang 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBintang1Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
