import 'package:flutter/material.dart';
import 'package:flutterapp/atsapp/generatedberandawidget/generated/GeneratedFotoProduk2Widget.dart';
import 'package:flutterapp/atsapp/generatedberandawidget/generated/GeneratedAddBasketWidget1.dart';
import 'package:flutterapp/atsapp/generatedberandawidget/generated/GeneratedNotebookSummerBreezeWidget.dart';
import 'package:flutterapp/atsapp/generatedberandawidget/generated/GeneratedRp13000Widget1.dart';
import 'package:flutterapp/atsapp/generatedberandawidget/generated/Generated1SetALatLukisLengkapWidget.dart';
import 'package:flutterapp/atsapp/generatedberandawidget/generated/GeneratedFotoProduk5Widget.dart';
import 'package:flutterapp/atsapp/generatedberandawidget/generated/GeneratedButtonBeliWidget2.dart';
import 'package:flutterapp/atsapp/generatedberandawidget/generated/GeneratedAddBasketWidget2.dart';
import 'package:flutterapp/atsapp/generatedberandawidget/generated/GeneratedButtonBeliWidget.dart';
import 'package:flutterapp/atsapp/generatedberandawidget/generated/GeneratedTrendingWidget.dart';
import 'package:flutterapp/atsapp/generatedberandawidget/generated/GeneratedRp14000Widget.dart';
import 'package:flutterapp/atsapp/generatedberandawidget/generated/GeneratedAddBasketWidget.dart';
import 'package:flutterapp/atsapp/generatedberandawidget/generated/GeneratedButtonBeliWidget3.dart';
import 'package:flutterapp/atsapp/generatedberandawidget/generated/GeneratedMenuWidget6.dart';
import 'package:flutterapp/atsapp/generatedberandawidget/generated/GeneratedFotoProduk4Widget.dart';
import 'package:flutterapp/atsapp/generatedberandawidget/generated/GeneratedBrushpen1Set10pcsWidget.dart';
import 'package:flutterapp/atsapp/generatedberandawidget/generated/GeneratedAddBasketWidget4.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/atsapp/generatedberandawidget/generated/GeneratedRp18000Widget.dart';
import 'package:flutterapp/atsapp/generatedberandawidget/generated/GeneratedButtonSearchWidget3.dart';
import 'package:flutterapp/atsapp/generatedberandawidget/generated/GeneratedDiskon50BacktoSchoolWidget.dart';
import 'package:flutterapp/atsapp/generatedberandawidget/generated/GeneratedDiskon30untuksemuaproduklohWidget.dart';
import 'package:flutterapp/atsapp/generatedberandawidget/generated/GeneratedRp16000Widget1.dart';
import 'package:flutterapp/atsapp/generatedberandawidget/generated/GeneratedButtonBeliWidget4.dart';
import 'package:flutterapp/atsapp/generatedberandawidget/generated/GeneratedRp45000Widget.dart';
import 'package:flutterapp/atsapp/generatedberandawidget/generated/GeneratedAddBasketWidget3.dart';
import 'package:flutterapp/atsapp/generatedberandawidget/generated/GeneratedPensilset7pcsWidget.dart';
import 'package:flutterapp/atsapp/generatedberandawidget/generated/GeneratedFotoProdukWidget3.dart';
import 'package:flutterapp/atsapp/generatedberandawidget/generated/GeneratedBerandaWidget1.dart';
import 'package:flutterapp/atsapp/generatedberandawidget/generated/GeneratedKalkulatorAjaibMatematikaWidget.dart';
import 'package:flutterapp/atsapp/generatedberandawidget/generated/GeneratedBannerWidget1.dart';
import 'package:flutterapp/atsapp/generatedberandawidget/generated/GeneratedButtonBeliWidget1.dart';
import 'package:flutterapp/atsapp/generatedberandawidget/generated/GeneratedFotoProduk3Widget.dart';
import 'package:flutterapp/atsapp/generatedberandawidget/generated/GeneratedBannerWidget.dart';

/* Frame Beranda
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBerandaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1123.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 375.0,
                      height: 1123.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 26.0,
                              top: 56.0,
                              right: null,
                              bottom: null,
                              width: 148.0,
                              height: 36.0,
                              child: GeneratedBerandaWidget1(),
                            ),
                            Positioned(
                              left: 35.0,
                              top: 97.0,
                              right: null,
                              bottom: null,
                              width: 135.0,
                              height: 190.00001525878906,
                              child: GeneratedBannerWidget(),
                            ),
                            Positioned(
                              left: 203.0,
                              top: 97.0,
                              right: null,
                              bottom: null,
                              width: 135.0,
                              height: 190.0,
                              child: GeneratedBannerWidget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.2853333333333333;

                                final double height =
                                    constraints.maxHeight * 0.0943900267141585;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.06666666666666667,
                                      y: constraints.maxHeight *
                                          0.377560106856634,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedFotoProdukWidget3(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.2853333333333333;

                                final double height =
                                    constraints.maxHeight * 0.0943900267141585;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.06666666666666667,
                                      y: constraints.maxHeight *
                                          0.5004452359750667,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedFotoProduk2Widget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.2853333333333333;

                                final double height =
                                    constraints.maxHeight * 0.0943900267141585;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.06666666666666667,
                                      y: constraints.maxHeight *
                                          0.6233303650934996,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedFotoProduk3Widget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.2853333333333333;

                                final double height =
                                    constraints.maxHeight * 0.0943900267141585;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.06666666666666667,
                                      y: constraints.maxHeight *
                                          0.7462154942119323,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedFotoProduk4Widget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.2853333333333333;

                                final double height =
                                    constraints.maxHeight * 0.0943900267141585;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.06666666666666667,
                                      y: constraints.maxHeight *
                                          0.8691006233303651,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedFotoProduk5Widget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 26.0,
                              top: 382.0,
                              right: null,
                              bottom: null,
                              width: 128.0,
                              height: 30.0,
                              child: GeneratedTrendingWidget(),
                            ),
                            Positioned(
                              left: 36.0,
                              top: 305.0,
                              right: null,
                              bottom: null,
                              width: 142.0,
                              height: 46.0,
                              child:
                                  GeneratedDiskon30untuksemuaproduklohWidget(),
                            ),
                            Positioned(
                              left: 203.0,
                              top: 305.0,
                              right: null,
                              bottom: null,
                              width: 101.0,
                              height: 42.0,
                              child: GeneratedDiskon50BacktoSchoolWidget(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 426.0,
                              right: null,
                              bottom: null,
                              width: 191.0,
                              height: 14.0,
                              child: GeneratedNotebookSummerBreezeWidget(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 458.0,
                              right: null,
                              bottom: null,
                              width: 93.0,
                              height: 21.0,
                              child: GeneratedRp16000Widget1(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 593.0,
                              right: null,
                              bottom: null,
                              width: 93.0,
                              height: 21.0,
                              child: GeneratedRp45000Widget(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 727.0,
                              right: null,
                              bottom: null,
                              width: 93.0,
                              height: 21.0,
                              child: GeneratedRp13000Widget1(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 870.0,
                              right: null,
                              bottom: null,
                              width: 93.0,
                              height: 21.0,
                              child: GeneratedRp14000Widget(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 1008.0,
                              right: null,
                              bottom: null,
                              width: 93.0,
                              height: 21.0,
                              child: GeneratedRp18000Widget(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 562.0,
                              right: null,
                              bottom: null,
                              width: 162.0,
                              height: 22.0,
                              child: Generated1SetALatLukisLengkapWidget(),
                            ),
                            Positioned(
                              left: 200.0,
                              top: 503.0,
                              right: null,
                              bottom: null,
                              width: 78.0,
                              height: 27.0,
                              child: GeneratedButtonBeliWidget(),
                            ),
                            Positioned(
                              left: 200.0,
                              top: 645.0,
                              right: null,
                              bottom: null,
                              width: 78.0,
                              height: 27.0,
                              child: GeneratedButtonBeliWidget1(),
                            ),
                            Positioned(
                              left: 200.0,
                              top: 779.0,
                              right: null,
                              bottom: null,
                              width: 78.0,
                              height: 27.0,
                              child: GeneratedButtonBeliWidget2(),
                            ),
                            Positioned(
                              left: 200.0,
                              top: 915.0,
                              right: null,
                              bottom: null,
                              width: 78.0,
                              height: 27.0,
                              child: GeneratedButtonBeliWidget3(),
                            ),
                            Positioned(
                              left: 200.0,
                              top: 1055.0,
                              right: null,
                              bottom: null,
                              width: 78.0,
                              height: 27.0,
                              child: GeneratedButtonBeliWidget4(),
                            ),
                            Positioned(
                              left: 154.0,
                              top: 699.0,
                              right: null,
                              bottom: null,
                              width: 145.0,
                              height: 23.0,
                              child: GeneratedBrushpen1Set10pcsWidget(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 840.0,
                              right: null,
                              bottom: null,
                              width: 109.0,
                              height: 20.0,
                              child: GeneratedPensilset7pcsWidget(),
                            ),
                            Positioned(
                              left: 156.0,
                              top: 978.0,
                              right: null,
                              bottom: null,
                              width: 178.0,
                              height: 20.0,
                              child: GeneratedKalkulatorAjaibMatematikaWidget(),
                            ),
                            Positioned(
                              left: 69.0,
                              top: 21.0,
                              right: null,
                              bottom: null,
                              width: 268.0,
                              height: 35.0,
                              child: GeneratedButtonSearchWidget3(),
                            ),
                            Positioned(
                              left: 26.0,
                              top: 25.0,
                              right: null,
                              bottom: null,
                              width: 25.0,
                              height: 25.0,
                              child: GeneratedMenuWidget6(),
                            ),
                            Positioned(
                              left: 158.0,
                              top: 503.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child: GeneratedAddBasketWidget(),
                            ),
                            Positioned(
                              left: 158.0,
                              top: 646.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child: GeneratedAddBasketWidget1(),
                            ),
                            Positioned(
                              left: 158.0,
                              top: 777.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child: GeneratedAddBasketWidget2(),
                            ),
                            Positioned(
                              left: 158.0,
                              top: 915.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child: GeneratedAddBasketWidget3(),
                            ),
                            Positioned(
                              left: 158.0,
                              top: 1056.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child: GeneratedAddBasketWidget4(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
